Investigation 2024 12 02 staging
folio-org/mod-camunda pull request #128
Opened 2024-12-05 21:50 UTC by kaladay

This resolves the original problem described in TAMULib/fw-registry#397.

Upon upgrading to Poppy, the mapping functionality provided by external FOLIO modules does not work because the `SET_CONTRIBUTOR_TYPE_ID_BY_CODE_OR_NAME` and `TRIM_PUNCTUATION` are out of date or missing.

The `author.` is from the `100.e` from the MARC record should now be converted.
The normalization functions will strip out the punctuation, like the period `.`, and then map the name `author` into a matching UUID.

The error `22 Unprocessable Entity: "{"errors":[{"message":"must match \"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$\"","type":"1","code":"javax.validation.constraints.Pattern.message","parameters":[{"key":"contributors[0].contributorTypeId","value":"author."}]}]}` (which does not come from mod-camunda, but instead some other module via OKAPI) no longer happens.

see: https://github.com/folio-org/data-import-processing-core/blob/42b8d49510f64694a5094a2e353af45b258ee1cf/src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java#L330
see: https://github.com/folio-org/data-import-processing-core/blob/42b8d49510f64694a5094a2e353af45b258ee1cf/src/main/java/org/folio/processing/mapping/defaultmapper/processor/functions/NormalizationFunction.java#L108

2024-12-10 14:15 UTC, wwelling approved these changes

2024-12-10 15:54 UTC, rmathew1011 commented on src/main/java/org/folio/rest/camunda/utility/OkapiRestTemplate.java
> +  private static final String OKAPI_TENENT_HEADER = "X-Okapi-Tenant";
OKAPI_TENANT_HEADER

2024-12-10 15:56 UTC, rmathew1011 requested changes
A typo - rename  OKAPI_TENENT_HEADER to OKAPI_TENANT_HEADER

2024-12-10 20:21 UTC, wwelling commented on src/main/java/org/folio/rest/camunda/utility/OkapiRestTemplate.java
> +  private static final String OKAPI_TENENT_HEADER = "X-Okapi-Tenant";
```suggestion
  private static final String OKAPI_TENANT_HEADER = "X-Okapi-Tenant";
```

2024-12-10 20:22 UTC, wwelling commented on src/main/java/org/folio/rest/camunda/utility/OkapiRestTemplate.java
> +        headers.set(OKAPI_TENENT_HEADER, tenant);
```suggestion
        headers.set(OKAPI_TENANT_HEADER, tenant);
```

2024-12-10 20:23 UTC, wwelling commented on src/main/java/org/folio/rest/camunda/utility/OkapiRestTemplate.java
> +  private static final String OKAPI_TENENT_HEADER = "X-Okapi-Tenant";
Done.

2024-12-10 21:31 UTC, rmathew1011 approved these changes

2024-12-11 22:21 UTC, wwelling commented on src/main/java/org/folio/rest/camunda/config/CamundaTenantInit.java
>    @Autowired
This annotation is unnecessary.

2024-12-11 22:24 UTC, wwelling approved these changes

2024-12-17 15:57 UTC, wwelling approved these changes

2024-12-17 17:00 UTC, merged